/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\model.glb -t -o .\components\hero\Duythaidev.tsx -r public 
*/
'use client'

import * as THREE from "three";
import React, { JSX, useEffect, useRef, useState } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    AvatarBody: THREE.SkinnedMesh;
    AvatarLeftCornea: THREE.SkinnedMesh;
    AvatarLeftEyeball: THREE.SkinnedMesh;
    AvatarRightCornea: THREE.SkinnedMesh;
    AvatarRightEyeball: THREE.SkinnedMesh;
    AvatarTeethUpper: THREE.SkinnedMesh;
    glasses: THREE.SkinnedMesh;
    outfit_bottom: THREE.SkinnedMesh;
    outfit_shoes: THREE.SkinnedMesh;
    outfit_top: THREE.SkinnedMesh;
    AvatarEyelashes: THREE.SkinnedMesh;
    AvatarHead: THREE.SkinnedMesh;
    AvatarTeethLower: THREE.SkinnedMesh;
    Hips: THREE.Bone;
  };
  materials: {
    AvatarBody: THREE.MeshStandardMaterial;
    AvatarLeftCornea: THREE.MeshStandardMaterial;
    AvatarLeftEyeball: THREE.MeshStandardMaterial;
    AvatarRightCornea: THREE.MeshStandardMaterial;
    AvatarRightEyeball: THREE.MeshStandardMaterial;
    AvatarTeethUpper: THREE.MeshStandardMaterial;
    glasses: THREE.MeshStandardMaterial;
    outfit_bottom: THREE.MeshStandardMaterial;
    outfit_shoes: THREE.MeshStandardMaterial;
    outfit_top: THREE.MeshStandardMaterial;
    AvatarEyelashes: THREE.MeshStandardMaterial;
    AvatarHead: THREE.MeshStandardMaterial;
    AvatarTeethLower: THREE.MeshStandardMaterial;
  };
};

const ANIMATIONS_URL = {
  idle: "/animations/idle.fbx",
};

const ANIMATION_NAMES = {
  idle: "Idle",
};

const mapPhonemeToMorphTarget = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_E",
  D: "viseme_aa",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_nn",
  X: "viseme_sil",
};

type Phoneme = keyof typeof mapPhonemeToMorphTarget;

interface MouthCue {
  start: number;
  end: number;
  value: Phoneme;
}

export interface AvatarProps {
  mouthCues?: MouthCue[];
  audioRef?: React.RefObject<HTMLAudioElement | null>;
}

export function DuythaidevModel(
  props: JSX.IntrinsicElements["group"] & AvatarProps,
) {
  const { mouthCues, audioRef } = props;

  const { scene } = useGLTF("/models/model.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;

  const [currentAnimation, setCurrentAnimation] = useState(
    ANIMATION_NAMES.idle,
  );

  const { animations: idle } = useFBX(ANIMATIONS_URL.idle);

  idle[0].name = ANIMATION_NAMES.idle;

  const modelRef = useRef<THREE.Object3D | null>(null);

  const { actions } = useAnimations([idle[0]], modelRef);

  useEffect(() => {
    if (!actions || !actions[currentAnimation]) return;
    console.log("actions", actions);
    actions[currentAnimation].reset().fadeIn(0.5).play();
    return () => {
      actions[currentAnimation]?.fadeOut(0.5);
    };
  }, [currentAnimation]);

  useFrame(() => {
    const audio = audioRef?.current;
    if (!audio || !audioRef?.current) return;
    if (audioRef.current.paused || audioRef.current.ended) return;

    const currentFrame = audio.currentTime;

    const head = nodes.AvatarHead;
    const dict = head.morphTargetDictionary;

    if (!dict) return;

    const currentMouthCue = mouthCues?.find(
      (mc) => currentFrame > mc.start && currentFrame < mc.end,
    );

    const activeTargetName = currentMouthCue
      ? mapPhonemeToMorphTarget[currentMouthCue.value]
      : "viseme_sil";

    // Lerp toàn bộ viseme mỗi frame: viseme đang active -> 1, còn lại -> 0
    Object.values(mapPhonemeToMorphTarget).forEach((visemeName) => {
      // với từng value trong object mapPhonemeToMorphTarget
      const idxViseme = dict[visemeName];
      // ví dụ: dict = { viseme_A: 0, viseme_B: 1, ...}
      // -> key 'viseme_A' có index 0

      const targetValue = visemeName === activeTargetName ? 1 : 0;
      // targetValue là 1 nếu visemeName đang active, còn lại là 0

      if (idxViseme === undefined || !head.morphTargetInfluences) return;

      // lerp từng frame tăng dần value của target lên tiệm cận đến 1 (hoặc 0 khi không active)
      head.morphTargetInfluences[idxViseme] = THREE.MathUtils.lerp(
        head.morphTargetInfluences[idxViseme],
        targetValue,
        0.15,
      );
    });
  });

  return (
    <group {...props} dispose={null} ref={modelRef}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.AvatarBody.geometry}
        material={materials.AvatarBody}
        skeleton={nodes.AvatarBody.skeleton}
      />
      <skinnedMesh
        geometry={nodes.AvatarLeftCornea.geometry}
        material={materials.AvatarLeftCornea}
        skeleton={nodes.AvatarLeftCornea.skeleton}
      />
      <skinnedMesh
        geometry={nodes.AvatarLeftEyeball.geometry}
        material={materials.AvatarLeftEyeball}
        skeleton={nodes.AvatarLeftEyeball.skeleton}
      />
      <skinnedMesh
        geometry={nodes.AvatarRightCornea.geometry}
        material={materials.AvatarRightCornea}
        skeleton={nodes.AvatarRightCornea.skeleton}
      />
      <skinnedMesh
        geometry={nodes.AvatarRightEyeball.geometry}
        material={materials.AvatarRightEyeball}
        skeleton={nodes.AvatarRightEyeball.skeleton}
      />
      <skinnedMesh
        geometry={nodes.AvatarTeethUpper.geometry}
        material={materials.AvatarTeethUpper}
        skeleton={nodes.AvatarTeethUpper.skeleton}
      />
      <skinnedMesh
        geometry={nodes.glasses.geometry}
        material={materials.glasses}
        skeleton={nodes.glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.outfit_bottom.geometry}
        material={materials.outfit_bottom}
        skeleton={nodes.outfit_bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.outfit_shoes.geometry}
        material={materials.outfit_shoes}
        skeleton={nodes.outfit_shoes.skeleton}
      />
      <skinnedMesh
        geometry={nodes.outfit_top.geometry}
        material={materials.outfit_top}
        skeleton={nodes.outfit_top.skeleton}
      />
      <skinnedMesh
        name="AvatarEyelashes"
        geometry={nodes.AvatarEyelashes.geometry}
        material={materials.AvatarEyelashes}
        skeleton={nodes.AvatarEyelashes.skeleton}
        morphTargetDictionary={nodes.AvatarEyelashes.morphTargetDictionary}
        morphTargetInfluences={nodes.AvatarEyelashes.morphTargetInfluences}
      />
      <skinnedMesh
        name="AvatarHead"
        geometry={nodes.AvatarHead.geometry}
        material={materials.AvatarHead}
        skeleton={nodes.AvatarHead.skeleton}
        morphTargetDictionary={nodes.AvatarHead.morphTargetDictionary}
        morphTargetInfluences={nodes.AvatarHead.morphTargetInfluences}
      />
      <skinnedMesh
        name="AvatarTeethLower"
        geometry={nodes.AvatarTeethLower.geometry}
        material={materials.AvatarTeethLower}
        skeleton={nodes.AvatarTeethLower.skeleton}
        morphTargetDictionary={nodes.AvatarTeethLower.morphTargetDictionary}
        morphTargetInfluences={nodes.AvatarTeethLower.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/model.glb");
